# Generated by Django 4.1.7 on 2023-03-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plants_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='plants',
            field=models.ManyToManyField(to='main_app.plants'),
        ),
    ]
